apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops-workshop
  template:
    metadata:
      labels:
        app: devsecops-workshop
    spec:
      containers:
      - name: web
        image: ghcr.io/<user>/devsecops-workshop:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: ghcr-secret
